Repository Devcourse-BE6-8-3-Team5/Backend, pull requests merged in 2025-08, with the labels that each got.

#5 [fix] 퀴즈 도메인 테스트코드 수정
  src/main/resources/application-test.yml
  src/test/java/com/back/backend/domain/quiz/daily/controller/DailyQuizControllerTest.java
  src/test/java/com/back/backend/domain/quiz/detail/controller/DetailQuizControllerTest.java
  src/test/java/com/back/backend/domain/quiz/fact/controller/FactQuizControllerTest.java
Labels: fix

#10 [Refactor] global healthController 코틀린 변환 #1
  build.gradle.kts
  src/main/java/com/back/global/controller/HealthController.java
  src/main/java/com/back/global/controller/HealthController.kt
Labels: refactor

#11 [feat] extensions 추가
  src/main/java/com/back/standard/extensions/extensions.kt
Labels: feat

#23 [refactor] AiConfig 코틀린 변환
  src/main/java/com/back/global/ai/AiConfig.java
  src/main/java/com/back/global/ai/AiConfig.kt
Labels: feat

#31 [feat] AiServiceTest, DetailQuizProcessorTest 작성#1
  src/test/java/com/back/backend/global/ai/AiServiceTest.java
  src/test/java/com/back/backend/global/ai/processor/DetailQuizProcessorTest.java
Labels: feat

#33 refactor : ServiceException, GlobalException handler convert#1
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/exception/ServiceException.kt
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.kt
Labels: refactor

#35 [refactor] AiService 코틀린 변환
  src/main/java/com/back/global/ai/AiService.java
  src/main/java/com/back/global/ai/AiService.kt
  src/test/java/com/back/backend/global/ai/AiServiceTest.java
Labels: refactor

#39 [Refactor]RsData,LevelSystem 변환#1
  src/main/java/com/back/domain/news/common/service/NewsPageService.kt
  src/main/java/com/back/global/controller/HealthController.kt
  src/main/java/com/back/global/exception/ServiceException.kt
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.kt
  src/main/java/com/back/global/rsData/RsData.java
  src/main/java/com/back/global/rsData/RsData.kt
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomOAuth2UserService.java
  src/main/java/com/back/global/util/LevelSystem.java
  src/main/java/com/back/global/util/LevelSystem.kt
Labels: refactor

#46 [fix] TestRq - NullPointerException 에러 해결
  src/test/java/com/back/backend/global/rq/TestRq.java
Labels: fix

#52 [Refactor] 뉴스도메인 dto 코틀린 전환 및 서비스 코드 전환
  src/main/java/com/back/dev/service/DevTestNewsService.java
  src/main/java/com/back/domain/news/common/dto/AnalyzedNewsDto.java
  src/main/java/com/back/domain/news/common/dto/AnalyzedNewsDto.kt
  src/main/java/com/back/domain/news/common/dto/KeywordGenerationReqDto.java
  src/main/java/com/back/domain/news/common/dto/KeywordGenerationReqDto.kt
  src/main/java/com/back/domain/news/common/dto/KeywordGenerationResDto.java
  src/main/java/com/back/domain/news/common/dto/KeywordGenerationResDto.kt
  src/main/java/com/back/domain/news/common/dto/KeywordWithType.java
  src/main/java/com/back/domain/news/common/dto/KeywordWithType.kt
  src/main/java/com/back/domain/news/common/dto/NaverNewsDto.java
  src/main/java/com/back/domain/news/common/dto/NaverNewsDto.kt
  src/main/java/com/back/domain/news/common/dto/NewsDetailDto.java
  src/main/java/com/back/domain/news/common/dto/NewsDetailDto.kt
  src/main/java/com/back/domain/news/common/entity/KeywordHistory.java
  src/main/java/com/back/domain/news/common/entity/KeywordHistory.kt
  src/main/java/com/back/domain/news/common/service/KeywordHistoryService.java
  src/main/java/com/back/domain/news/common/service/KeywordHistoryService.kt
  src/main/java/com/back/domain/news/real/dto/RealNewsDto.kt
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.kt
  src/main/java/com/back/domain/news/today/entity/TodayNews.java
  src/main/java/com/back/domain/news/today/entity/TodayNews.kt
  src/main/java/com/back/global/ai/processor/KeywordGeneratorProcessor.java
  src/test/java/com/back/backend/domain/news/real/controller/NewsControllerTest.java
  src/test/java/com/back/backend/domain/news/real/controller/NewsControllerTest.kt
Labels: refactor

#56 [refactor] DailyQuiz dto 코틀린 변환
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizAnswerDto.java
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizAnswerDto.kt
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizDto.java
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizDto.kt
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizWithHistoryDto.java
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizWithHistoryDto.kt
  src/main/java/com/back/domain/quiz/daily/entity/DailyQuiz.java
  src/main/java/com/back/domain/quiz/detail/entity/DetailQuiz.java
  src/test/java/com/back/backend/domain/quiz/daily/controller/DailyQuizControllerTest.java
Labels: refactor

#64 [refactor] FactQuiz dto 코틀린 변환#1
  src/main/java/com/back/domain/news/fake/entity/FakeNews.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizAnswerDto.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizAnswerDto.kt
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDto.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDto.kt
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDtoWithNewsContent.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDtoWithNewsContent.kt
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizWithHistoryDto.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizWithHistoryDto.kt
  src/main/java/com/back/domain/quiz/fact/entity/FactQuiz.java
  src/test/java/com/back/backend/domain/quiz/detail/controller/DetailQuizControllerTest.java
  src/test/java/com/back/backend/domain/quiz/fact/controller/FactQuizControllerTest.java
Labels: refactor

#73 [refactor] SecurityConfig & CustomAuthenticationFilter 코틀린 전환
  src/main/java/com/back/global/rq/Rq.kt
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.kt
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityConfig.kt
  src/main/java/com/back/global/standard/util/Ut.kt
Labels: refactor

#75 [refactor] Member관련 DTO 코틀린 변환#1
  src/main/java/com/back/domain/member/member/dto/MemberDto.java
  src/main/java/com/back/domain/member/member/dto/MemberDto.kt
  src/main/java/com/back/domain/member/member/dto/MemberWithAuthDto.java
  src/main/java/com/back/domain/member/member/dto/MemberWithAuthDto.kt
  src/main/java/com/back/domain/member/member/dto/MemberWithInfoDto.java
  src/main/java/com/back/domain/member/member/dto/MemberWithInfoDto.kt
  src/main/java/com/back/domain/member/member/dto/MemberWithRankDto.java
  src/main/java/com/back/domain/member/member/dto/MemberWithRankDto.kt
Labels: refactor

#76 [refactor] AdminMember, MemberController 코틀린 변환#1
  src/main/java/com/back/domain/member/member/controller/AdmMemberController.java
  src/main/java/com/back/domain/member/member/controller/AdmMemberController.kt
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/controller/MemberController.kt
Labels: refactor
